import React from 'react';
import { 
  X, 
  DownloadCloud, 
  Printer, 
  Bot, 
  CheckCircle2, 
  TrendingUp, 
  DollarSign, 
  ShieldCheck, 
  Sparkles,
  FileText
} from 'lucide-react';
import { SwarmState } from '../services/agentEngine';
import { soundFx } from '../services/soundEffects';

interface ReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  state: SwarmState;
}

export const ReportModal: React.FC<ReportModalProps> = ({
  isOpen,
  onClose,
  state
}) => {
  if (!isOpen) return null;

  const handlePrint = () => {
    soundFx.playClick();
    window.print();
  };

  const handleExportCSV = () => {
    soundFx.playSuccess();
    const rows = [
      ['Metric', 'Value'],
      ['Total 30D Revenue', `$${state.metrics.totalRevenue.toFixed(2)}`],
      ['Agent-Driven Revenue Uplift', `+${state.metrics.revenueUpliftPercentage}%`],
      ['Total Recovered Abandoned Carts', `$${state.metrics.recoveredRevenue.toFixed(2)}`],
      ['Pricing Elasticity Gains', `$${state.metrics.pricingGains.toFixed(2)}`],
      ['Ad Efficiency Gains', `$${state.metrics.adEfficiencyGains.toFixed(2)}`],
      ['Blended ROAS', `${state.metrics.blendedRoas.toFixed(2)}x`],
      ['Cart Recovery Winback Rate', `${state.metrics.cartRecoveryRate.toFixed(1)}%`],
      ['Gross Profit Margin', `${state.metrics.grossMargin.toFixed(1)}%`],
      ['Merchant Hours Saved', `${state.metrics.hoursSavedToday} hrs`],
      ['Total Autonomous Actions Executed', `${state.metrics.totalAgentActions}`]
    ];

    const csvContent = 'data:text/csv;charset=utf-8,' + rows.map(e => e.join(',')).join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `ShopPilot_AI_Growth_Report_${Date.now()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const totalIncrementalRev = state.metrics.recoveredRevenue + state.metrics.pricingGains + state.metrics.adEfficiencyGains;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div 
        className="modal-content"
        onClick={(e) => e.stopPropagation()}
        style={{ width: '800px', maxWidth: '95vw', padding: '28px', background: '#0a101f' }}
      >
        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: '20px', borderBottom: '1px solid var(--border-subtle)', paddingBottom: '16px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <div style={{ width: '42px', height: '42px', borderRadius: '10px', background: 'linear-gradient(135deg, #10B981 0%, #6366F1 100%)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <Bot size={24} color="#fff" />
            </div>
            <div>
              <h2 style={{ fontSize: '1.25rem', fontWeight: 800, color: '#FFFFFF' }}>
                Executive Commerce Growth & Swarm Audit Report
              </h2>
              <p style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>
                Generated by ShopPilot AI Autonomous Orchestration Engine
              </p>
            </div>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <button
              onClick={handleExportCSV}
              className="btn btn-secondary"
              style={{ padding: '7px 12px', fontSize: '0.78rem' }}
            >
              <DownloadCloud size={14} />
              Export CSV
            </button>
            <button
              onClick={handlePrint}
              className="btn btn-primary"
              style={{ padding: '7px 12px', fontSize: '0.78rem' }}
            >
              <Printer size={14} />
              Print PDF
            </button>
            <button
              onClick={onClose}
              style={{ background: 'transparent', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', padding: '4px' }}
            >
              <X size={20} />
            </button>
          </div>
        </div>

        {/* Report Content */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '18px', maxHeight: '560px', overflowY: 'auto' }}>
          
          {/* Executive Summary Card */}
          <div style={{ background: 'rgba(16, 185, 129, 0.08)', border: '1px solid rgba(16, 185, 129, 0.3)', borderRadius: '12px', padding: '16px 20px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
              <Sparkles size={18} color="#10B981" />
              <h3 style={{ fontSize: '1rem', fontWeight: 700, color: '#34D399' }}>
                Executive Performance Summary
              </h3>
            </div>
            <p style={{ fontSize: '0.82rem', color: 'var(--text-main)', lineHeight: 1.5 }}>
              Over the last 30-day billing cycle, the ShopPilot AI Swarm generated an incremental <strong>+${totalIncrementalRev.toLocaleString()}</strong> in net top-line revenue, representing a <strong>+{state.metrics.revenueUpliftPercentage}%</strong> expansion over unassisted baseline store velocity. Autonomous media optimization raised blended ROAS to <strong>{state.metrics.blendedRoas.toFixed(2)}x</strong>, while automated WhatsApp recovery reclaimed <strong>${state.metrics.recoveredRevenue.toLocaleString()}</strong> in high-intent abandoned checkouts.
            </p>
          </div>

          {/* Metric Breakdown Table */}
          <div style={{ background: 'rgba(5, 9, 18, 0.75)', border: '1px solid var(--border-subtle)', borderRadius: '12px', padding: '16px' }}>
            <h4 style={{ fontSize: '0.92rem', fontWeight: 700, marginBottom: '12px', color: '#FFFFFF' }}>
              Core Growth Key Performance Indicators
            </h4>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '12px' }}>
              
              <div style={{ background: 'rgba(15, 23, 42, 0.8)', padding: '10px 14px', borderRadius: '8px' }}>
                <div style={{ fontSize: '0.72rem', color: 'var(--text-dim)' }}>Total Net Revenue</div>
                <div className="mono" style={{ fontSize: '1.2rem', fontWeight: 800, color: '#fff' }}>${state.metrics.totalRevenue.toLocaleString()}</div>
                <div style={{ fontSize: '0.68rem', color: '#34D399' }}>+{state.metrics.revenueUpliftPercentage}% agent-driven</div>
              </div>

              <div style={{ background: 'rgba(15, 23, 42, 0.8)', padding: '10px 14px', borderRadius: '8px' }}>
                <div style={{ fontSize: '0.72rem', color: 'var(--text-dim)' }}>Cart Recovery Winback</div>
                <div className="mono" style={{ fontSize: '1.2rem', fontWeight: 800, color: '#F472B6' }}>+${state.metrics.recoveredRevenue.toLocaleString()}</div>
                <div style={{ fontSize: '0.68rem', color: 'var(--text-dim)' }}>{state.metrics.cartRecoveryRate}% recovery rate</div>
              </div>

              <div style={{ background: 'rgba(15, 23, 42, 0.8)', padding: '10px 14px', borderRadius: '8px' }}>
                <div style={{ fontSize: '0.72rem', color: 'var(--text-dim)' }}>Pricing Arbitrage Gains</div>
                <div className="mono" style={{ fontSize: '1.2rem', fontWeight: 800, color: '#38BDF8' }}>+${state.metrics.pricingGains.toLocaleString()}</div>
                <div style={{ fontSize: '0.68rem', color: '#38BDF8' }}>+4.2% gross margin</div>
              </div>

              <div style={{ background: 'rgba(15, 23, 42, 0.8)', padding: '10px 14px', borderRadius: '8px' }}>
                <div style={{ fontSize: '0.72rem', color: 'var(--text-dim)' }}>Ad Efficiency Uplift</div>
                <div className="mono" style={{ fontSize: '1.2rem', fontWeight: 800, color: '#818CF8' }}>+${state.metrics.adEfficiencyGains.toLocaleString()}</div>
                <div style={{ fontSize: '0.68rem', color: '#818CF8' }}>{state.metrics.blendedRoas.toFixed(2)}x blended ROAS</div>
              </div>

            </div>
          </div>

          {/* Swarm Sub-Agent Audit Table */}
          <div style={{ background: 'rgba(5, 9, 18, 0.75)', border: '1px solid var(--border-subtle)', borderRadius: '12px', padding: '16px' }}>
            <h4 style={{ fontSize: '0.92rem', fontWeight: 700, marginBottom: '12px', color: '#FFFFFF' }}>
              Specialized Agent Operations Audit
            </h4>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
              {state.agents.map((agent) => (
                <div key={agent.id} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '8px 12px', background: 'rgba(15, 23, 42, 0.5)', borderRadius: '6px', fontSize: '0.8rem' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                    <div style={{ width: '8px', height: '8px', borderRadius: '50%', background: agent.color }}></div>
                    <span style={{ fontWeight: 700, color: '#fff' }}>{agent.name}</span>
                    <span style={{ color: 'var(--text-dim)' }}>({agent.role})</span>
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                    <span className="mono" style={{ color: 'var(--text-muted)' }}>{agent.actionsCount} actions</span>
                    <span className="mono" style={{ fontWeight: 700, color: agent.color }}>{agent.roiImpact}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>

        </div>
      </div>
    </div>
  );
};
